[profile.default]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
solc-version = "0.8.24"
evm_version = 'shanghai'
gas_reports = ['APIAccount']
remappings = ['@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/',
'@chainlink/contracts/=node_modules/@chainlink/contracts/',
'forge-std/=lib/forge-std/src/',
]
chain_id = 1
# force = true
# DEFAULT VALUE: 9223372036854775807         
gas_limit = "18446744073709551615"                     
gas_price = 0
# File reading permissions
fs_permissions = [{ access = "read-write", path = "./"}]
optimizer_runs = 200

[fuzz]
runs = 100

[invariant]
runs = 100
depth = 250
fail_on_revert = false

[profile.default.fmt]
line_length=80
tab_width=4
bracket_spacing=false
quote_style='double'
number_underscore='thousands'
# `params_first`, `attributes_first` (by default) or `all`
multiline_func_header='attributes_first'

[rpc_endpoints]
# goerli = "${GOERLI_RPC_URL}"
# mumbai = "${MUMBAI_RPC_URL}"


# See more config options https://github.com/gakonst/foundry/tree/master/config
